/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 13
#define LARGE_STATE_COUNT 9
#define SYMBOL_COUNT 15
#define ALIAS_COUNT 0
#define TOKEN_COUNT 11
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 2
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LF = 1,
  sym_line_comment = 2,
  sym_macro_header = 3,
  sym_string = 4,
  sym_variable = 5,
  sym_word = 6,
  sym_number = 7,
  sym_operator = 8,
  sym_punctuation = 9,
  sym_whitespace = 10,
  sym_source_file = 11,
  sym_content = 12,
  aux_sym_source_file_repeat1 = 13,
  aux_sym_content_repeat1 = 14,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LF] = "\n",
  [sym_line_comment] = "line_comment",
  [sym_macro_header] = "macro_header",
  [sym_string] = "string",
  [sym_variable] = "variable",
  [sym_word] = "word",
  [sym_number] = "number",
  [sym_operator] = "operator",
  [sym_punctuation] = "punctuation",
  [sym_whitespace] = "whitespace",
  [sym_source_file] = "source_file",
  [sym_content] = "content",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_content_repeat1] = "content_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LF] = anon_sym_LF,
  [sym_line_comment] = sym_line_comment,
  [sym_macro_header] = sym_macro_header,
  [sym_string] = sym_string,
  [sym_variable] = sym_variable,
  [sym_word] = sym_word,
  [sym_number] = sym_number,
  [sym_operator] = sym_operator,
  [sym_punctuation] = sym_punctuation,
  [sym_whitespace] = sym_whitespace,
  [sym_source_file] = sym_source_file,
  [sym_content] = sym_content,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_content_repeat1] = aux_sym_content_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [sym_line_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_macro_header] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_variable] = {
    .visible = true,
    .named = true,
  },
  [sym_word] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_punctuation] = {
    .visible = true,
    .named = true,
  },
  [sym_whitespace] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_content] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_content_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 4,
  [8] = 5,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(12);
      ADVANCE_MAP(
        '\n', 13,
        '"', 1,
        '%', 29,
        '/', 24,
        ':', 28,
        '<', 26,
        '=', 25,
        '>', 25,
        '\t', 30,
        ' ', 30,
        '#', 2,
        '@', 2,
        '*', 23,
        '+', 23,
        '-', 23,
      );
      if ((0x0b <= lookahead && lookahead <= '\r')) SKIP(0);
      if (('(' <= lookahead && lookahead <= ',') ||
          lookahead == ';' ||
          lookahead == '[' ||
          lookahead == ']') ADVANCE(27);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(21);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(17);
      if (lookahead == '\\') ADVANCE(10);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == '[') ADVANCE(9);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(19);
      END_STATE();
    case 3:
      if (lookahead == ']') ADVANCE(18);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(3);
      END_STATE();
    case 4:
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(5);
      END_STATE();
    case 5:
      if (lookahead == 'C' ||
          lookahead == 'c') ADVANCE(8);
      END_STATE();
    case 6:
      if (lookahead == 'M' ||
          lookahead == 'm') ADVANCE(4);
      END_STATE();
    case 7:
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(16);
      END_STATE();
    case 8:
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(7);
      END_STATE();
    case 9:
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ']') ADVANCE(3);
      END_STATE();
    case 10:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(1);
      END_STATE();
    case 11:
      if (eof) ADVANCE(12);
      if (lookahead == '\n') ADVANCE(14);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(11);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_LF);
      if (lookahead == '\n') ADVANCE(13);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(30);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_LF);
      if (lookahead == '\n') ADVANCE(14);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_line_comment);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(15);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_macro_header);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_variable);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_variable);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(19);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(22);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(21);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(22);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_operator);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_operator);
      if (lookahead == '/') ADVANCE(15);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_operator);
      if (lookahead == '=') ADVANCE(23);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_operator);
      if (lookahead == '=' ||
          lookahead == '>') ADVANCE(23);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_punctuation);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_punctuation);
      if (lookahead == '=') ADVANCE(23);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_punctuation);
      if (lookahead == '@') ADVANCE(6);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_whitespace);
      if (lookahead == '\n') ADVANCE(13);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(30);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 11},
  [10] = {.lex_state = 11},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 11},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LF] = ACTIONS(1),
    [sym_line_comment] = ACTIONS(1),
    [sym_macro_header] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [sym_variable] = ACTIONS(1),
    [sym_word] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_operator] = ACTIONS(1),
    [sym_punctuation] = ACTIONS(1),
    [sym_whitespace] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(11),
    [sym_content] = STATE(9),
    [aux_sym_source_file_repeat1] = STATE(2),
    [aux_sym_content_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_LF] = ACTIONS(5),
    [sym_line_comment] = ACTIONS(7),
    [sym_macro_header] = ACTIONS(7),
    [sym_string] = ACTIONS(7),
    [sym_variable] = ACTIONS(7),
    [sym_word] = ACTIONS(7),
    [sym_number] = ACTIONS(7),
    [sym_operator] = ACTIONS(7),
    [sym_punctuation] = ACTIONS(7),
    [sym_whitespace] = ACTIONS(7),
  },
  [STATE(2)] = {
    [sym_content] = STATE(10),
    [aux_sym_source_file_repeat1] = STATE(3),
    [aux_sym_content_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(9),
    [anon_sym_LF] = ACTIONS(11),
    [sym_line_comment] = ACTIONS(7),
    [sym_macro_header] = ACTIONS(7),
    [sym_string] = ACTIONS(7),
    [sym_variable] = ACTIONS(7),
    [sym_word] = ACTIONS(7),
    [sym_number] = ACTIONS(7),
    [sym_operator] = ACTIONS(7),
    [sym_punctuation] = ACTIONS(7),
    [sym_whitespace] = ACTIONS(7),
  },
  [STATE(3)] = {
    [sym_content] = STATE(12),
    [aux_sym_source_file_repeat1] = STATE(3),
    [aux_sym_content_repeat1] = STATE(7),
    [ts_builtin_sym_end] = ACTIONS(13),
    [anon_sym_LF] = ACTIONS(15),
    [sym_line_comment] = ACTIONS(18),
    [sym_macro_header] = ACTIONS(18),
    [sym_string] = ACTIONS(18),
    [sym_variable] = ACTIONS(18),
    [sym_word] = ACTIONS(18),
    [sym_number] = ACTIONS(18),
    [sym_operator] = ACTIONS(18),
    [sym_punctuation] = ACTIONS(18),
    [sym_whitespace] = ACTIONS(18),
  },
  [STATE(4)] = {
    [aux_sym_content_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(21),
    [anon_sym_LF] = ACTIONS(23),
    [sym_line_comment] = ACTIONS(25),
    [sym_macro_header] = ACTIONS(25),
    [sym_string] = ACTIONS(25),
    [sym_variable] = ACTIONS(25),
    [sym_word] = ACTIONS(25),
    [sym_number] = ACTIONS(25),
    [sym_operator] = ACTIONS(25),
    [sym_punctuation] = ACTIONS(25),
    [sym_whitespace] = ACTIONS(25),
  },
  [STATE(5)] = {
    [aux_sym_content_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(27),
    [anon_sym_LF] = ACTIONS(29),
    [sym_line_comment] = ACTIONS(31),
    [sym_macro_header] = ACTIONS(31),
    [sym_string] = ACTIONS(31),
    [sym_variable] = ACTIONS(31),
    [sym_word] = ACTIONS(31),
    [sym_number] = ACTIONS(31),
    [sym_operator] = ACTIONS(31),
    [sym_punctuation] = ACTIONS(31),
    [sym_whitespace] = ACTIONS(31),
  },
  [STATE(6)] = {
    [ts_builtin_sym_end] = ACTIONS(13),
    [anon_sym_LF] = ACTIONS(34),
    [sym_line_comment] = ACTIONS(34),
    [sym_macro_header] = ACTIONS(34),
    [sym_string] = ACTIONS(34),
    [sym_variable] = ACTIONS(34),
    [sym_word] = ACTIONS(34),
    [sym_number] = ACTIONS(34),
    [sym_operator] = ACTIONS(34),
    [sym_punctuation] = ACTIONS(34),
    [sym_whitespace] = ACTIONS(34),
  },
  [STATE(7)] = {
    [aux_sym_content_repeat1] = STATE(8),
    [anon_sym_LF] = ACTIONS(23),
    [sym_line_comment] = ACTIONS(36),
    [sym_macro_header] = ACTIONS(36),
    [sym_string] = ACTIONS(36),
    [sym_variable] = ACTIONS(36),
    [sym_word] = ACTIONS(36),
    [sym_number] = ACTIONS(36),
    [sym_operator] = ACTIONS(36),
    [sym_punctuation] = ACTIONS(36),
    [sym_whitespace] = ACTIONS(36),
  },
  [STATE(8)] = {
    [aux_sym_content_repeat1] = STATE(8),
    [anon_sym_LF] = ACTIONS(29),
    [sym_line_comment] = ACTIONS(38),
    [sym_macro_header] = ACTIONS(38),
    [sym_string] = ACTIONS(38),
    [sym_variable] = ACTIONS(38),
    [sym_word] = ACTIONS(38),
    [sym_number] = ACTIONS(38),
    [sym_operator] = ACTIONS(38),
    [sym_punctuation] = ACTIONS(38),
    [sym_whitespace] = ACTIONS(38),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 2,
    ACTIONS(9), 1,
      ts_builtin_sym_end,
    ACTIONS(41), 1,
      anon_sym_LF,
  [7] = 2,
    ACTIONS(41), 1,
      anon_sym_LF,
    ACTIONS(43), 1,
      ts_builtin_sym_end,
  [14] = 1,
    ACTIONS(45), 1,
      ts_builtin_sym_end,
  [18] = 1,
    ACTIONS(41), 1,
      anon_sym_LF,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(9)] = 0,
  [SMALL_STATE(10)] = 7,
  [SMALL_STATE(11)] = 14,
  [SMALL_STATE(12)] = 18,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [9] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [15] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [18] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_content, 1, 0, 0),
  [23] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_content, 1, 0, 0),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_content_repeat1, 2, 0, 0),
  [29] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_content_repeat1, 2, 0, 0),
  [31] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_content_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [34] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [36] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [38] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_content_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [45] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_syntec_macro_spike(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "syntec_macro_spike",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 0,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
