/**
 * Export Rust parity baseline fixture as JSON (Rust golden file).
 *
 * R1.2 Stage B (2026-09-22) retired the JS analyzer; the original
 * `exportRustParityBaseline.js` (which read a JS-generated fixture) and the
 * v3.1.0 fixture were removed during v4.x cleanup. This replacement generates
 * the baseline by running the **Rust CLI** itself against the CASES /
 * NAVIGATION_CASES / FORMAT_CASES defined in `scripts/compareRustCore.js`.
 *
 * The resulting fixture is a "golden file": it captures the Rust analyzer's
 * current output as the expected baseline. `compare:rust` then re-runs the
 * Rust CLI and asserts the output is unchanged, guarding against silent
 * regressions in the Rust core (no JS truth source remains post-R1.2).
 *
 * Re-generate this fixture only when the Rust analyzer's output is
 * *intentionally* changed (new diagnostic, refined range, etc.). After
 * regenerating, commit the updated fixture and document the change in the
 * PR description and CHANGELOG.
 *
 * Usage:
 *   node scripts/exportRustBaseline.js [outputPath]
 *
 * Defaults to `tests/fixtures/rust-parity-baseline.json`.
 * Honors the `SYNTEC_RUST_CLI` env var; otherwise uses the compare default.
 */

const fs = require('fs');
const path = require('path');

const {
  CASES,
  NAVIGATION_CASES,
  FORMAT_CASES,
  getRustDiagnostics,
  getRustNavigation,
  getRustEdit
} = require('./compareRustCore');

const SCHEMA_VERSION = 1;
const DEFAULT_OUTPUT_PATH = path.join(
  __dirname,
  '..',
  'tests',
  'fixtures',
  'rust-parity-baseline.json'
);

/**
 * Resolve the Rust CLI path. compareRustCore.js reads `SYNTEC_RUST_CLI` and
 * falls back to
 * `crates/syntec-core/target/x86_64-pc-windows-gnu/debug/syntec-core-cli[.exe]`;
 * we mirror that here so a single env var drives both export and compare.
 */
function resolveRustCli() {
  const fromEnv = process.env.SYNTEC_RUST_CLI;
  if (fromEnv) return fromEnv;
  // Mirror compareRustCore.js DEFAULT_RUST_CLI exactly.
  return path.join(
    __dirname,
    '..',
    'crates',
    'syntec-core',
    'target',
    'x86_64-pc-windows-gnu',
    'debug',
    process.platform === 'win32' ? 'syntec-core-cli.exe' : 'syntec-core-cli'
  );
}

/**
 * Build the baseline fixture by running the Rust CLI for every case.
 * Each case stores only the `expected` payload that `compare:rust` later
 * compares against (diagnostics array / navigation object / edit descriptor).
 */
function buildBaseline(rustCli) {
  if (!fs.existsSync(rustCli)) {
    throw new Error(`Rust core CLI not found: ${rustCli}; build it before exporting the baseline`);
  }

  const cases = CASES.map((testCase) => {
    const expected = getRustDiagnostics(rustCli, testCase.text);
    return { name: testCase.name, text: testCase.text, expected };
  });

  const navigationCases = NAVIGATION_CASES.map((testCase) => {
    const expected = getRustNavigation(rustCli, testCase.uri, testCase.text);
    return { name: testCase.name, uri: testCase.uri, text: testCase.text, expected };
  });

  const formatCases = FORMAT_CASES.map((testCase) => {
    const expected = getRustEdit(rustCli, testCase.text);
    return { name: testCase.name, text: testCase.text, expected };
  });

  return {
    schemaVersion: SCHEMA_VERSION,
    generatedAt: new Date().toISOString(),
    generator: 'scripts/exportRustBaseline.js (Rust CLI golden file)',
    note: 'Generated by running the Rust core CLI. R1.2 Stage B retired the JS analyzer; this fixture is the Rust self-consistency baseline (no JS truth source).',
    cases,
    navigationCases,
    formatCases
  };
}

function main(argv = process.argv.slice(2)) {
  const outputPath = argv[0] ? path.resolve(argv[0]) : DEFAULT_OUTPUT_PATH;
  const rustCli = resolveRustCli();
  const baseline = buildBaseline(rustCli);
  fs.mkdirSync(path.dirname(outputPath), { recursive: true });
  fs.writeFileSync(outputPath, JSON.stringify(baseline, null, 2) + '\n', 'utf8');
  const summary = {
    cases: baseline.cases.length,
    navigationCases: baseline.navigationCases.length,
    formatCases: baseline.formatCases.length,
    schemaVersion: baseline.schemaVersion,
    generatedAt: baseline.generatedAt,
    rustCli
  };
  console.info(`Rust parity baseline written: ${outputPath}`);
  console.info(JSON.stringify(summary, null, 2));
}

if (require.main === module) main();

module.exports = {
  buildBaseline,
  resolveRustCli,
  DEFAULT_OUTPUT_PATH,
  SCHEMA_VERSION
};
