const DiagnosticCode = {
  MISSING_SEMICOLON: 'SYNTEC_MISSING_SEMICOLON',
  CONTROL_STRUCTURE_TRAILING_SEMICOLON: 'SYNTEC_CONTROL_STRUCTURE_TRAILING_SEMICOLON'
};

module.exports = { DiagnosticCode };