const DiagnosticCode = {
  MISSING_SEMICOLON: 'SYNTEC_MISSING_SEMICOLON',
  CONTROL_STRUCTURE_TRAILING_SEMICOLON: 'SYNTEC_CONTROL_STRUCTURE_TRAILING_SEMICOLON',
  UNSUPPORTED_ELSIF: 'SYNTEC_UNSUPPORTED_ELSIF',
  UNSUPPORTED_DEFAULT: 'SYNTEC_UNSUPPORTED_DEFAULT',
  UNSUPPORTED_DIV: 'SYNTEC_UNSUPPORTED_DIV',
  UNSUPPORTED_EQUALITY_OPERATOR: 'SYNTEC_UNSUPPORTED_EQUALITY_OPERATOR',
  UNSUPPORTED_INEQUALITY_OPERATOR: 'SYNTEC_UNSUPPORTED_INEQUALITY_OPERATOR',
  UNSUPPORTED_LOGICAL_AND_OPERATOR: 'SYNTEC_UNSUPPORTED_LOGICAL_AND_OPERATOR',
  UNSUPPORTED_LOGICAL_OR_OPERATOR: 'SYNTEC_UNSUPPORTED_LOGICAL_OR_OPERATOR',
  UNSUPPORTED_PERCENT_OPERATOR: 'SYNTEC_UNSUPPORTED_PERCENT_OPERATOR',
  UNSUPPORTED_LOGICAL_NOT_OPERATOR: 'SYNTEC_UNSUPPORTED_LOGICAL_NOT_OPERATOR',
  UNSUPPORTED_COMPOUND_ASSIGNMENT: 'SYNTEC_UNSUPPORTED_COMPOUND_ASSIGNMENT',
  UNSUPPORTED_INCREMENT: 'SYNTEC_UNSUPPORTED_INCREMENT',
  UNSUPPORTED_FANUC_COMPARISON: 'SYNTEC_UNSUPPORTED_FANUC_COMPARISON'
};

module.exports = { DiagnosticCode };